#include "tms_robot_ui/main_window.hpp"
#include "ui_main_window.h" // Generated by Qt AUTOUIC from resource/main_window.ui

#include <ament_index_cpp/get_package_share_directory.hpp>
#include <QBrush>
#include <QDateTime>
#include <QHeaderView>
#include <QHBoxLayout>
#include <QVBoxLayout>
#include <QWidget>

MainWindow::MainWindow(rclcpp::Node::SharedPtr node, QWidget * parent) 
: QMainWindow(parent), node_(node), 
ui_(std::make_unique<Ui::MainWindow>()), 
ros_bridge_(new RosBridge(node, this)), 
rviz_widget_(nullptr), 
camera_view_widget_(nullptr), 
ros_spin_timer_(nullptr) { 
  buildUi(); 
  connectSignals();
  loadSelectedTree();
  ros_spin_timer_ = new QTimer(this);
  connect(ros_spin_timer_, &QTimer::timeout, this, [this]() {
    rclcpp::spin_some(node_);
  });
  ros_spin_timer_->start(20);
}

MainWindow::~MainWindow() = default;

void MainWindow::buildUi() {
  ui_->setupUi(this);
  task_selector_ = ui_->task_selector;
  zero_button_ = ui_->zero_button;
  start_button_ = ui_->start_button;
  cancel_button_ = ui_->cancel_button;
  force_label_ = ui_->force_label;
  distance_label_ = ui_->distance_label;
  state_label_ = ui_->state_label;
  active_node_label_ = ui_->active_node_label;
  bt_tree_widget_ = ui_->bt_tree_widget;
  log_text_ = ui_->log_text;
  task_selector_->clear();
  task_selector_->addItem("inspect");
  task_selector_->addItem("patrol");
  task_selector_->addItem("move_arm_home");
  bt_tree_widget_->setColumnCount(2);
  bt_tree_widget_->setHeaderLabels({"BT Node", "Status"});
  bt_tree_widget_->header()->setSectionResizeMode(QHeaderView::Stretch);
  log_text_->setReadOnly(true);
  rviz_widget_ = new RvizWidget(ui_->rviz_container);
  auto * rviz_layout = ui_->rviz_container->layout();
  if (!rviz_layout) {
    rviz_layout = new QVBoxLayout(ui_->rviz_container);
    rviz_layout->setContentsMargins(0, 0, 0, 0);
  }
  rviz_layout->addWidget(rviz_widget_);
  camera_view_widget_ = new CameraViewWidget(node_, ui_->camera_container);
  camera_view_widget_->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
  auto * camera_layout = ui_->camera_container->layout();
  if (!camera_layout) {
    camera_layout = new QVBoxLayout(ui_->camera_container);
    camera_layout->setContentsMargins(0, 0, 0, 0);
  }
  camera_layout->addWidget(camera_view_widget_);
}

void MainWindow::connectSignals() {
  connect(zero_button_, &QPushButton::clicked, this, &MainWindow::onZeroClicked);
  connect(start_button_, &QPushButton::clicked, this, &MainWindow::onStartClicked);
  connect(cancel_button_, &QPushButton::clicked, this, &MainWindow::onCancelClicked);
  connect(task_selector_, qOverload<int>(&QComboBox::currentIndexChanged), this, [this](int) { loadSelectedTree(); });
  connect(ros_bridge_, &RosBridge::taskStateUpdated, this, &MainWindow::onTaskStateUpdated); 
  connect(ros_bridge_, &RosBridge::btNodeStatusUpdated, this, &MainWindow::onBtNodeStatusUpdated);
  connect(ros_bridge_, &RosBridge::logMessage, this, &MainWindow::onLogMessage);
  connect(ros_bridge_, &RosBridge::forceUpdated, this, &MainWindow::onForceUpdated);
  connect(ros_bridge_, &RosBridge::distanceUpdated, this, &MainWindow::onDistanceUpdated);
}

QString MainWindow::selectedTaskName() const {
  return task_selector_->currentText();
}

QString MainWindow::selectedTreePath() const {
  const auto share_dir = QString::fromStdString(ament_index_cpp::get_package_share_directory("tms_robot_control"));
  if (selectedTaskName() == "inspect") {
    return share_dir + "/tree/inspect_tree.xml";
  }
  if (selectedTaskName() == "patrol") {
    return share_dir + "/tree/patrol_tree.xml";
  }
  return share_dir + "/tree/move_arm_home.xml";
}

void MainWindow::loadSelectedTree() {
  loadTreeIntoWidget(selectedTreePath());
}

void MainWindow::onZeroClicked() {
  ros_bridge_->zeroFTS();
}

void MainWindow::onStartClicked() {
  ros_bridge_->startTask(selectedTaskName());
}

void MainWindow::onCancelClicked() {
  ros_bridge_->cancelTask();
}

void MainWindow::onTaskStateUpdated(const QString &, 
const QString & overall_state, 
const QString & active_node, 
const QString & message) { 
  Q_UNUSED(message);
  state_label_->setText("State: " + overall_state); 
  active_node_label_->setText("Active Node: " + active_node);
}

void MainWindow::onBtNodeStatusUpdated(const QString & node_name, 
const QString &, 
const QString & status) { 
  if (!node_items_.contains(node_name)) { 
    return; 
  } 
  auto * item = node_items_[node_name];
  item->setText(1, status); 
  setItemColor(item, status); 
}

void MainWindow::onLogMessage(const QString & msg) {
  const auto now = QDateTime::currentDateTime().toString("hh:mm:ss");
  log_text_->append(QString("[%1] %2").arg(now, msg));
}

void MainWindow::onForceUpdated(const QString & msg) {
  force_label_->setText("Force sensor Z: " + msg + " N");
}

void MainWindow::onDistanceUpdated(const QString & msg) {
  distance_label_->setText("Distance sensor: " + msg + " mm");
}

void MainWindow::loadTreeIntoWidget(const QString & xml_path) {
  bt_tree_widget_->clear();
  node_items_.clear();
  QFile file(xml_path);
  if (!file.open(QIODevice::ReadOnly)) {
    return;
  }
  QDomDocument doc;
  if (!doc.setContent(&file)) {
    return;
  }
  const auto root = doc.documentElement();
  QDomElement tree_elem;
  auto child = root.firstChild();
  while (!child.isNull()) {
    if (child.isElement() && child.toElement().tagName() == "BehaviorTree") {
      tree_elem = child.toElement();
      break;
    }
    child = child.nextSibling();
  }
  if (tree_elem.isNull()) {
    return;
  }
  auto node = tree_elem.firstChild();
  while (!node.isNull()) {
    if (node.isElement()) {
      auto * top = buildTreeItemFromDom(node.toElement());
      if (top) {
        bt_tree_widget_->addTopLevelItem(top);
      }
    }
    node = node.nextSibling();
  }
  bt_tree_widget_->expandAll();
}

QTreeWidgetItem * MainWindow::buildTreeItemFromDom(const QDomElement & element) {
  QString node_name = element.hasAttribute("name") ? element.attribute("name") : element.tagName();
  auto * item = new QTreeWidgetItem({node_name, "IDLE"});
  node_items_[node_name] = item;
  auto child = element.firstChild();
  while (!child.isNull()) {
    if (child.isElement()) {
      auto * sub = buildTreeItemFromDom(child.toElement());
      if (sub) {
        item->addChild(sub);
      }
    }
    child = child.nextSibling();
  }
  return item;
}

void MainWindow::setItemColor(QTreeWidgetItem * item, const QString & status) {
  QColor color = Qt::white;
  if (status == "RUNNING") color = QColor(255, 235, 130);
  else if (status == "SUCCESS") color = QColor(170, 255, 170);
  else if (status == "FAILURE") color = QColor(255, 170, 170);
  item->setBackground(0, QBrush(color));
  item->setBackground(1, QBrush(color));
}